### ISSUE TITLE
Tracker: Release PowerBi reports to production

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#311]
- [x] WorkOrder
- [x] Checklist
- [x] Handover 
- [x] Loop
- [x] SWCR (No records for OGP)
- [x] CC Punch Analytics
- [x] CC Overview 
- [x] Tags
- [x] Commissioning Task
- [x] Mechanical Completion
- [x] Atex Inspection (No production data for OGP)
