### ISSUE TITLE
Tracker: Procosys urls

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#417]
# Handover [data-proxy]

## Table
- [x] Comm pkg

## Sidesheet
- [x] Comm pkg
- [x] Mc pkg
- [x] Workorder
- [x] Unsigned task
- [x] Unsigned action
- [x] Punch
- [x] NCR (broken in fusion aswell)
- [x] Query

# Workorder 

## Table
- [x] WorkorderNo

## Sidesheet
- [x] WorkorderNo
- [x] Mc pkg
- [x] Comm pkg
- [x] MCCR tag no

# MC [data-proxy]

## Table
- [ ] Mc pkg
- [ ] Comm pkg
- [ ] Area?

## Sidesheet
- [ ] Mc pkg
- [ ] Comm pkg
- [x] NCR (broken link as in fusion)
- [x] Workorder
- [x] Punch

# SWCR (data-proxy)

## Table
- [ ] Swcr

## Sidesheet
- [ ]  Swcr

# Loop
## Table
- [x] LoopTag
- [x] Comm pkg
- [x] Mc pkg
- [x] Formular type

## Sidesheet
- [x] Comm pkg
- [x] Mc pkg
- [x] Workorders

# Punch

## Table
- [x] Punch
- [x] Form type
- [x] Tag
- [x] Commpkg
- [x] Workorder

## Sidesheet
- [x] Form type
- [x] Tag
- [x] Comm pkg
- [x] Mc pkg

**Comment by Gustav-Eikaas** [comment]
FYI @ken-mellem Tracker for procosys links available in the different apps

**Comment by aman-riaz** [comment]
@Gustav-Eikaas  Can you please add names of the APIs / Views where you need the URL-ids so @BenSvend can add them in. It is easier for us when we know which view this is about.

**Comment by BenSvend** [comment]
After speaking with @Gustav-Eikaas we've concluded that this task is done.
