### ISSUE TITLE
Follow-up Handover app (#328)

### ISSUE THREAD

**Issue by espenkalle** [equinor/cc-components#436]
## Pre-decessor:

- equinor/cc-components#328

## Todo

After showing the app we identified the following issues to be addressed immediately

- [x] #434 
- [x] Additional fields for grouping - https://github.com/equinor/fusion-workspace/pull/451 https://github.com/equinor/fusion-data-gateway/pull/207
- [x] equinor/lighthouse#290 - https://github.com/equinor/cc-components/pull/468
- [x] https://github.com/equinor/lighthouse/issues/200
- [x] https://github.com/equinor/cc-components/pull/546
- [x] https://github.com/equinor/cc-components/pull/547
