### ISSUE TITLE
👑 Epic: Implement Heat Trace app

### ISSUE THREAD

**Issue by ken-mellem** [equinor/cc-components#520]
## Description

This item is a placeholder/Epic for **Heat Tracel** - Scale the application for Project Portal. See the list below.

## App

- [x] equinor/cc-components#445
- [x] equinor/fusion-data-gateway#164 

## PBI

- [x] equinor/cc-components#419

**Comment by MagnusGjosund** [comment]
More or less done. The rest of the smallfixes in collected in another issue https://github.com/equinor/cc-components/issues/661
