### ISSUE TITLE
📇 Tracker: Enable 3D for CC applications

### ISSUE THREAD

**Issue by ken-mellem** [equinor/cc-components#578]
## 3D support in CC-applications

For relevant apps which has tags, makes 3D relevant. Expand list as needed. 
Create sub issues where relevant, e.g. where backend/frontend job is needed.

- [x] #582
- [x] #583
- [x] #940
- [x] #941
- [x] #942
- [x] #943

**Comment by kjellhaaland** [comment]
After some discussions with @espenkalle, this is the list of actions needed to complete the 3D component.

- [ ] Implement support for different environments (CI/CD) 
This is currently hard-coded
See widget/{widget}/config.ts for more details on how it is set up

- [ ] Fix support for multiple facilities. 
Currently the first element in the list of facilities are taken

- [ ] Widgets does not support the current implementation of CustomActions
If custom actions are needed, a new widget has to be created and the actions defined in the widget.

- [ ] Add API endpoints for fetching which tags that are relevant for 3D.
This is straight-forward for WorkOrder and Punch, but other applications such as Handover, HeatTrace and Pipetest is more complex. The endpoint should return the tags that are relevant for 3D.

Notes to self:
- Jone is the PO for this
- Chris is the "master of widgets and Echo" 👑

**Comment by kjellhaaland** [comment]
After a lot of back-and-forth with how to implement this, it was decided that we skip using widgets for this implementation.

This decision is documented in an ADR: https://github.com/equinor/lighthouse/blob/main/docs/decisions/004-modelviewer-bundling.md

There have been a lot of rewrites of the ModelViewer component, since the handover from Espen.
This includes:
- Removing all widget-spesific functionality
- Support for lazy-loading the ModelViewer for more optimal bundle sizes
- Restructured most of the code. (Removed almost all useEffects, useState, etc.)
- Added a way of using environment variables, etc.
- ...

**Comment by kjellhaaland** [comment]
Moving this to Done, as 3D now is implemented in all applications described in the issue 🎉
