### ISSUE TITLE
✨: New "GroupBy" design in workspace

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#624]
## Expected outcome

Familiar and intuitive groupBy functionality.

## Business Value / Developer Experience

Today grouping is hidden behind a menu.
We want upgrade experience from fusion to projectPortal to be as smooth as possible. Hiding the groupBy will probably lead to frustration and support cases where to find the group function.
GroupBy needs to be more visible and intuative. 

UX has already created a new design for this.
@chriispychiicken : Can you add a link to the new design?

## Acceptance Criteria

- [x] Implemented according to Figma design

## Successor

- [x] equinor/fusion-project-portal#382
- [x] equinor/fusion-workspace#488
- [ ] https://github.com/equinor/fusion-workspace/pull/494
- [ ] equinor/cc-components#625

**Comment by espenkalle** [comment]
UX: https://github.com/orgs/equinor/projects/415/views/7?filterQuery=group&pane=issue&itemId=40444830

**Comment by espenkalle** [comment]
Issue closes automatically when the linked branch is closed. Still needs testing

**Comment by espenkalle** [comment]
New discoveries: 
- Must be open by default
- Open/closed state must be remembered (localstorage)
