### ISSUE TITLE
📋Workorder : Feature checklist

### ISSUE THREAD

**Issue by espenkalle** [equinor/cc-components#716]
### Feature Completeness Evaluation
When evaluating feature completeness, ensure that the app embodies the best aspects of JC Portal, Fusion, and Project Portal. It should use their most effective features and design elements to create an optimal user experience.

When list is exhausted and issues created this issue should be closed.

### Filter
- [ ] Correct implementation of filter logic.
- [ ] Quickfilters are intuitive and efficient.
- [ ] Filter responsiveness and performance.
- [ ] User interface alignment with best aspects of JC Portal, Fusion, and Project Portal.

### KPI
- [ ] Accurate calculation and display of Amount.
- [ ] Reliable representation of Values.
- [ ] Updates correctly with filtering.

### Garden
- [ ] Correct sorting.
- [ ] Logical grouping options with correct default value.
- [ ] Visual appeal and clarity of information for Garden items.

### Grid
- [ ] Columns are correctly implemented and aligned.
- [ ] Sorting functionality implemented.
- [ ] Appropriate column widths.

### Sidesheet
- [ ] Details information display is accurate and complete.
- [ ] Links are functional and correctly directed.
- [ ] Tabs are implemented and correct.
- [ ] Aesthetic and functional consistency with the main application.

### Usability and User Experience
- [ ] Responsiveness
- [ ] User feedback and error messages are clear and helpful.
- [ ] Overall ease of use.
