### ISSUE TITLE
📋Mechanical Completion : Feature checklist

### ISSUE THREAD

**Issue by espenkalle** [equinor/cc-components#743]
### Feature Completeness Evaluation
When evaluating feature completeness, ensure that the app embodies the best aspects of JC Portal, Fusion, and Project Portal. It should use their most effective features and design elements to create an optimal user experience.

When list is exhausted and issues created this issue should be closed.

### Filter
- [ ] Correct implementation of filter logic.
- [ ] Quickfilters are intuitive and efficient.
- [ ] Filter responsiveness and performance.
- [ ] User interface alignment with best aspects of JC Portal, Fusion, and Project Portal.

### KPI
- [ ] Accurate calculation and display of Amount.
- [ ] Reliable representation of Values.
- [ ] Updates correctly with filtering.

### Garden
- [ ] Correct sorting.
- [ ] Logical grouping options with correct default value.
- [ ] Visual appeal and clarity of information for Garden items.

### Grid
- [ ] Columns are correctly implemented and aligned.
- [ ] Sorting functionality implemented.
- [ ] Appropriate column widths.

### Sidesheet
- [ ] Details information display is accurate and complete.
- [ ] Links are functional and correctly directed.
- [ ] Tabs are implemented and correct.
- [ ] Aesthetic and functional consistency with the main application.

### Usability and User Experience
- [ ] Responsiveness
- [ ] User feedback and error messages are clear and helpful.
- [ ] Overall ease of use.

### Data  (?)
- [ ] Issues regarding data quality?

**Comment by ken-mellem** [comment]
![image](https://github.com/equinor/cc-components/assets/110427825/f7f57e09-faad-4190-8a2e-77c1b80272c9)
Double link?`

**Comment by ken-mellem** [comment]
Column width table should probably be looked at globally.

**Comment by espenkalle** [comment]
Bookmarks implemented.
And in test :)

**Comment by ken-mellem** [comment]
> ![image](https://private-user-images.githubusercontent.com/110427825/289842234-3ad6dc47-5426-4e05-ac9c-53cdd3cb8ef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDgyMTUsIm5iZiI6MTcwMjQwNzkxNSwicGF0aCI6Ii8xMTA0Mjc4MjUvMjg5ODQyMjM0LTNhZDZkYzQ3LTU0MjYtNGUwNS1hYzljLTUzY2RkM2NiOGVmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxOTA1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWY0Mzc4M2EyMjY4OGI4NDljMmIxZmQ2ZWQwZmZiOGI3ZWFlMDBlMDcyZmIwZTg5NTNmMDhkOWJhMGFlNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qZzsDbHuGanzyf4xi5_qGvL0Dm1tCRR0I-jwT2oFKG8)

✅

**Comment by ken-mellem** [comment]
"Bookmarks" - this is how the system works.  I will make a tracker for to align Bookmark implementation cross apps.

**Comment by atlewee** [comment]
@espenkalle 
Disse kolonnene i checklist tab kan fjernes, da mc/commPk allerede alltid vises med link:
![image](https://github.com/equinor/cc-components/assets/11732817/7abafaaa-ce11-4044-941c-35731433f662)

**Comment by ken-mellem** [comment]
@atlewee the sidesheet tabs are re-used cross apps. If we remove this here, it will influence its use in Work Order. We note your comment - but we are pushing the button now!
