### ISSUE TITLE
🎁: Loop Rally testing

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#885]
## Expected outcome

![Image](https://github.com/equinor/cc-components/assets/73601851/53c022c5-49c0-406f-9b32-6376263bacab)

## Tasks
- [x] Checklist status, ok not centered in sideheet table and sidesheet
- [x] Progress bars not center aligned
- [x] Consolidate details in side sheet
- [x] Inconsistant height and padding in hanging gardens
- [x] Missing links in second details table in sidesheet
- [x] Clarify what filters should be visible
- [x] Clarify what sorting rule is needed
- [x] Update title to to match the handover page
- [x] Set default grouping to RFCC

**Comment by ken-mellem** [comment]
@kjellhaaland this is also perhaps a nice one for @EdwardBrunton ?

**Comment by EdwardBrunton** [comment]
@JoneUE could you clarify what you mean by "sorting rule?" and list what quick filters you want added?

**Comment by JoneUE** [comment]
Is it possible to sort on progress? if not just sort from lowest to highest number or a-z

Quick filters: Checklist Status, Content MC Status, Comm System, Form Responsible and Comm Pkg

**Comment by EdwardBrunton** [comment]
@JoneUE Do you have a specific metric for progress for loop? I can't see any simple property to use.
